[project]
name = "cep"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "passlib>=1.7.4",
    "pymysql>=1.1.2",
    "sqlalchemy>=2.0.44",
    "streamlit>=1.51.0",
]
